# This is for production container

version: "3"
services:
  ruby:
    env_file:
      # ESHOP_ENV is the env var in local shell, the value will be dev, uat or pro
      # $(ESHOP_ENV).env is the file which defined all env vars for the container
      - ./envfiles/pro.env
